services:
  irs-simulation:
    image: ghcr.io/collaborativeroboticslab/industrial-robots-and-systems-warehouse:humble
    environment:
      - PYTHONUNBUFFERED=1                # GUI related
      - DISPLAY                           # GUI related
      - QT_X11_NO_MITSHM=1                # GUI related
      - NVIDIA_VISIBLE_DEVICES=all        # GUI related
      - NVIDIA_DRIVER_CAPABILITIES=all    # GUI related
      - ROS_DOMAIN_ID=0
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw    # GUI related

  irs-openplc-runtime:
    image: ghcr.io/collaborativeroboticslab/industrial-robots-and-systems-openplc-runtime:humble
    restart: unless-stopped
    network_mode: host

  omron_moma_ros2:
    image: ghcr.io/collaborativeroboticslab/industrial-robots-and-systems-omron-moma:humble
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=0
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw