services:
  irs-openplc-editor:
    image: ghcr.io/collaborativeroboticslab/industrial-robots-and-systems-openplc-editor:humble
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./openplc_data:/editor_shared_folder